debug
zsz12251665/os-course-design pull request #2
Opened 2022-05-24 14:47 UTC by OmigaXm

1. 执行copy的时候没有判断文件名是否存在，会在同一目录下创建相同名字的文件。在cmd.cpp添加了判断是否重名的代码。

2. 在main.cpp中添加了我的姓名和学号。

3. main.cpp中对路径规范化处理的时候，对“../../”形式的路径处理有误，无法做到多级返回父目录。我觉得这部分代码没有必要实现，所以删掉了。如果这部分规范化是有确实需要的，就要修改一下多级“../”的处理。

2022-05-24 15:28 UTC, zsz12251665 commented
除了重名，还有父目录和文件名长度要检查，已一并建议修改

2022-05-25 02:59 UTC, zsz12251665 requested changes

2022-05-25 02:59 UTC, zsz12251665 commented on cmd.cpp
>  	INode dir_inode = getDirINode(selectINode(cwd_inode_num), des);
```suggestion
	if (strlen(getFilename(des)) > FILENAME_MAX_LENGTH) {
		printf("Error: The filename is too long!\n");
		return;
	}
	INode dir_inode = getDirINode(selectINode(cwd_inode_num), des);
	if (dir_inode.num == 0) {
		printf("Error: The path does not exist!\n");
		return;
	}
	if (getFileINode(selectINode(cwd_inode_num), des).num != 0) {
		printf("Error: \"%s\" already exists!\n", des);
		return;
	}
```

2022-05-25 02:59 UTC, zsz12251665 commented on main.cpp
> -	}
此处的确有问题，不过删掉后有几个地方需要修改：

- 要在创建文件/目录时检查文件名`getFilename()`的内容是否为`.`或`..`（比如`createFile /.. 1`为非法操作）
- 在删除目录的时候，目录名以`.`或`..`结尾的目录名不能直接以`getFilename(filename)`来确定要删除的文件名，需要改写这部分代码
- 同时，在`getDirINode()`中处理路径的方式也需要修改（需要加入检查：当`path`目标是文件时取上一层寻址的INode，当目标是目录时读取目录文件`..`条目获取父目录INode）

2022-05-25 03:29 UTC, OmigaXm reviewed
adopt new update about "cp"

2022-05-25 06:23 UTC, zsz12251665 commented on main.cpp
> -	}
```suggestion
	while (len > 1 && path[len - 1] == '.') {
		if (path[len - 2] == '/') {
			path[len == 2 ? 1 : len - 2] = '\0';
			len -= 2;
		}
	}
```

2022-05-25 06:33 UTC, zsz12251665 reviewed
在`createFile`和`createDir`中同样的地方也插入这段（`des`要改成对应的路径）

2022-05-25 06:33 UTC, zsz12251665 commented on cmd.cpp
> +	}
```suggestion
	}
	if (!strcmp(getFilename(des), "..")) {
		printf("Error: \"..\" is not a valid filename!\n");
		return;
	}
```

2022-05-25 13:45 UTC, zsz12251665 commented on main.cpp
> +		}else{
```suggestion
		} else {
```

2022-05-25 13:47 UTC, zsz12251665 approved these changes

2022-05-25 13:48 UTC, merged